### ISSUE TITLE
The use of "vertx.executeBlocking" in the vertx-jdbc-service can lead to a stuck system

### ISSUE THREAD

**Issue by ufoscout** [vert-x3/vertx-jdbc-service#12]
The thread pool to get a jbdc connection and the one to use it must not be the same otherwise the system can be blocked forever.
Simple scenario that reproduces the issue:
(Let's set worker pool size to 1 and max connection pool size also to 1 for simplicity)

1. A gets connection
2. A executes query 1
3. B tries to get connection - worker blocks max pool size reached
4. A tries to execute query 2 - queued because no available worker

-- deadlock

Possible solutions:

1. Time out on get connection
2. Refactor getConnection so it doesn't use executeBlocking

More info here:
https://groups.google.com/forum/?fromgroups#!topic/vertx-dev/E_xzrfBFVZQ

**Comment by purplefox** [comment]
I've changed getConnection to execute on a different thread to the worker in order to avoid this situation.
