### ISSUE TITLE
You must be joking

### ISSUE THREAD

**Issue by aliakhtar** [vert-x3/vertx-jdbc-service#7]
In M2, when you run a query via conn.query, you get each row contained within a JsonObject. This is reasonable, since then you can look up the results by column name. E.g if you intend to fill up a dto, you can do stuff like

`user.setEmail( result.getString("email") ); `

However I just upgraded to snapshot, and I see that this has been changed to a ResultSet (which is fine), but the resultSet has a getResult method, which returns a `List<JsonArray>` rather than a `List<JsonObject>`

I'm hoping that this was a mistake, and / or a `List<JsonObject>` method is soon to be added, or the snapshot build I have is old somehow. Because with a json array,  instead of doing `result.getString(colName)`, I have to look up the column name by the numeric index, and do `result.get( index)`.

That's what PHP had back in 2002 or so when you had to do `mysql_num_rows()` and look up the column by index. We're not going back to that, are we?

I'm ranting a bit because I just had to write a utility method for converting JsonArrays into JsonObjects, so that my existing code will continue to work. However the performance on that is going to be shit if that has to be done for each row in production.

Thanks.

**Comment by purplefox** [comment]
The trouble with the JsonObject approach is each row contains the field names. That means if you have a 10000 rows you have all the field names duplicated in memory 10000 times. This can make the memory footprint of the resultset a *lot* bigger and it means it will take a longer to serialize over the wire.

Maybe we can provide convenience methods on the ResultSet to retrieve the values by column name?

**Comment by aliakhtar** [comment]
I'd say that because this is the jdbc library, we should stick to jdbc conventions for this, which is to provide a way to get values by column name.

I can't think of many use cases where you'd really be loading 10,000 rows into memory. Most of the time you'd be paginating to load 10-100 rows at a time.

Its far more common that you'd want to look up columns by name (and would incur the performance penalty of looking it up by the index for each time), than the edge case of loading 10,000 rows at a time.

**Comment by aliakhtar** [comment]
Tim,

There's also another solution, if you do what JDBC does, i.e:

`while (resultSet.hasRows()`
`{ `
`     JsonObject row = resultSet.next();`
`}`

Then only one JsonObject at a time would be created, and there would be no memory issues.

But actually, even that isn't necessary, since you can just intern the key names, in which case the same string instances would be used for all 10,000 rows rather than a new instance being made for each row.

String intern support is very good in JDK 8, and that will completely resolve the performance concerns without having to give up the convenience of looking up values by the column name.

There's really no need to go back to the bad old days of arrays! :)

More info: http://java-performance.info/string-intern-in-java-6-7-8/

**Comment by purplefox** [comment]
I've added a method getRows() to return rows as Json object instances.

BTW, this GitHub issue is in the wrong repo - should be in vertx-sql-common :)
