### ISSUE TITLE
resultSet.getRows() is empty

### ISSUE THREAD

**Issue by ufoscout** [vert-x3/vertx-jdbc-service#9]
Dear all,

I'm playing with the code in the master and I found a strange behaviour with the resultSet.getRows() method that can be easily reproduced with this code (replace the table "users" with whatever table you want):
```
jdbcService.getConnection(handler -> {
			handler.result().query("select count(*) as count from users", result -> {
					logger.info("Found {} rows", result.result().getNumRows()); //prints 1
					logger.info("Results size {}", result.result().getResults().size()); //prints 1
					logger.info("Rows size {}", result.result().getRows().size()); //prints 0
			});
		});
```

There is no data in the getRows(); but, based on the documentation of vertx-sql-commons, it is supposed to contain a list of JsonObject populated with the results. I checked the available unit tests and it seems that that method is not tested.

**Comment by purplefox** [comment]
Hi Francesco,

In SQL,

SELECT COUNT(*) FROM ...

simply counts the number of rows - it does not return the rows 
themselves, so this seems like expected behaviour.

If you want to return the actual rows, you can use:

SELECT * FROM ....

**Comment by ufoscout** [comment]
Hi tim,

sorry but I don't agree with your analysis. 
In SQL a "select count(*) blablabla" returns exactly one row whose content is the desired count. So it does contain rows.
As a confirmation that this is a bug, if you execute "select * from users" instead of the count, you will see that the result.result().getRows() is always empty even if result.result().getResults() is not.

**Comment by ufoscout** [comment]
Hi Tim,

indeed it was a bug in the vertx-sql-common project. I fixed it and proposed a PR (https://github.com/vert-x3/vertx-sql-common/pull/3). 
I tested it locally and now it works with both "select * blablabla" and "select count(*) blablabla" :+1:

**Comment by purplefox** [comment]
Got it. Sorry - I misunderstood the original description and thought you were expecting all the rows to be returned

Thanks for the fix, will take a look soon :)
